version: "3"
services:
  mysql:
    image: mysql:8.3.0
    container_name: starry-mysql
    environment:
      MYSQL_DATABASE: starry
      MYSQL_ROOT_PASSWORD: Starry1024!.
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
